README.md

gizafoundation->zowe

---

config/zluxserver.json
doc/swagger/fileapi.json
js/zluxArgs.js

First cut of JSON & Args for mediation layer

---

plugins/com.rs.mvd.myplugin.json
plugins/org.zowe.zlux.sample.angular.json
plugins/org.zowe.zlux.sample.iframe.json

Required after merging https://github.com/zowe/sample-app/pull/2 and https://github.com/zowe/sample-iframe-app/pull/4

Updating names of sample apps

---

plugins/org.zowe.editor.json

Adding editor to list of plugins

---

doc/swagger/security-mgmt-api.yaml

1. Change the object type
2. Fix typos
3. Add group services

Add group services

---

doc/swagger/security-mgmt-api.yaml

Dryrun behavior not as described, boolean is opposite of doc

---

doc/swagger/fileapi.yaml
js/zluxArgs.js

As the Unix File API was changed, I updated the swagger documentation.

Updated Documentation

---

pluginDefaults/com.rs.mvd.ng2desktop/ui/launchbar/plugins/pinnedPlugins.json
pluginDefaults/org.zowe.zlux.ng2desktop/ui/launchbar/plugins/pinnedPlugins.json

Updated pinnedPlugins for new desktop ID and app IDs

---

.gitattributes
sonar-project.properties

These changes are minimal viable configurations to allow sonar to scan zlux and its submodules.
See https://github.com/zowe/zlux/pull/50

Add sonar project properties

---

doc/swagger/fileapi.yaml

Signed-off-by: Jordan Filteau <jfilteau@rocketsoftware.com>

Updated documentation for chunked uploads.

---

config/zluxserver.json
plugins/com.zowe.explorer.server.auth.json
plugins/com.zowe.explorer.server.proxy.json

Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>

Remove all references to explorer-server-auth

---

README.md
config/zluxserver.json
package.json
pluginDefaults/org.zowe.zlux.ng2desktop/ui/launchbar/plugins/pinnedPlugins.json
plugins/org.zowe.editor.json
plugins/org.zowe.terminal.tn3270.json
plugins/org.zowe.terminal.vt.json
plugins/org.zowe.zlux.auth.zosmf.json
plugins/org.zowe.zlux.auth.zss.json
plugins/org.zowe.zlux.proxy.zosmf.json
plugins/org.zowe.zlux.sample.angular.json
plugins/org.zowe.zlux.sample.iframe.json
plugins/org.zowe.zlux.sample.react.json
plugins/org.zowe.zosmf.workflows.json

That's the first part of https://github.com/zowe/zlux/issues/110
Signed-off-by: Dmitry Nikolaev <dnikolaev@rocketsoftware.com>

Remove all plugins which are not part of framework

---

plugins/org.zowe.zlux.ng2desktop.settings.json

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Added Zowe settings app into default installation

---

README.md
config/zluxserver.json
lib/zluxArgs.js
package.json
pluginDefaults/org.zowe.zlux.ng2desktop/ui/launchbar/plugins/pinnedPlugins.json
plugins/org.zowe.editor.json
plugins/org.zowe.terminal.tn3270.json
plugins/org.zowe.terminal.vt.json
plugins/org.zowe.zlux.auth.zosmf.json
plugins/org.zowe.zlux.auth.zss.json
plugins/org.zowe.zlux.proxy.zosmf.json
plugins/org.zowe.zlux.sample.angular.json
plugins/org.zowe.zlux.sample.iframe.json
plugins/org.zowe.zlux.sample.react.json
plugins/org.zowe.zosmf.workflows.json

Update master to v1.1.0
Signed-off-by: Dmitry Nikolaev dnikolaev@rocketsoftware.com

Update master to v1.1.0

---

doc/swagger/fileapi.yaml

Signed-off-by: Jordan Filteau <jfilteau@rocketsoftware.com>

Updated doc to include new mode query parameter.

---

doc/swagger/fileapi.yaml
package-lock.json

Updating swagger, adding missing package-lock

---

config/generate_zlux_certificates.sh
doc/swagger/fileapi.yaml
doc/swagger/security-mgmt-api.yaml

Signed-off-by: Reet Chowdhary <rchowdhary@rocketsoftware.com>

added license

---

zlux-app-server.ppf

Signed-off-by: Yan Li <raymondyanli@gmail.com>
@1000TurquoisePogs Please review this request.

adding AppScan config file

---

bin/nodeCluster.sh
bin/nodeServer.sh
bin/zssServer.sh

Signed-off-by: Vitek Vlcek <vitezslavvit.vlcek@broadcom.com>
Based on https://github.com/zowe/zowe-install-packaging/issues/385 added prefix for zssServer process

added specifics jobname  ${ZOWE_PREFIX}SZ1

---

config/zluxserver.json

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Added 'logLanguage' parameter to zluxserver.json

---

bin/install-app.bat
bin/install-app.sh

Add check for node before doing install app processing

---

doc/swagger/server-plugins-api.yaml

Add /plugin/ & /server/ Swagger documentation

Add /plugin/ & /server/ Swagger documentation

---

lib/zluxArgs.js

Removed conditional and just made CLI overriding JSON to be conditional

---

doc/swagger/server-plugins-api.yaml

Remove log patterns swagger as it doesn't work 100% yet

Commented out pattern POST for log as it doesn't work yet

---

lib/zluxArgs.js

Removed logout and config routes, they are unused

---

doc/swagger/server-plugins-api.yaml

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Made POST for logLevel more accurate

---

pluginDefaults/org.zowe.zlux.bootstrap/plugins/allowedPlugins.json

Added plugin default

---

bin/zssServer.sh

Signed-off-by: Sean Grady <sgrady@rocketsoftware.com>

Var dir is not valid, replaced with ZSS_SCRIPT_DIR

---

bin/nodeCluster.sh
bin/nodeServer.sh

Adding env var to force compatibility with older nodes

---

bin/app-server.bat
bin/app-server.sh

Fix for workers environment variables

---

bin/app-server.sh
bin/install-app.sh

Fixed rc printing that tee was hiding

---

bin/app-server.sh

Changed node -v to --version to work on older node versions

---

lib/zluxArgs.js

Re-add logout for zss. Still a bit of a hack but suits the need of logout for now.

Reintroduce the logout endpoint

---

bin/app-server.sh
bin/install-app.sh

Added missing autocvt environment var setting

---

lib/initInstance.js
lib/zluxArgs.js
lib/zluxServer.js

Zlux app server logging

---

lib/zluxArgs.js

Fix for unconditional tls override

---

lib/zluxArgs.js

WIP
Goes along with:
https://github.com/zowe/zss/pull/161
https://github.com/zowe/zowe-common-c/pull/128
https://github.com/zowe/zlux-platform/pull/52
https://github.com/zowe/zss-auth/pull/29
https://github.com/zowe/zlux-server-framework/pull/181
https://github.com/zowe/zlux-app-manager/pull/193

Password Reset

---

lib/initInstance.js
lib/upgradeInstance.js

Add ability to upgrade server configuration

---

bin/convert-env.sh

This pull request implements the following feature:
- Add SSO token name and label to convert-env.sh for use with ZSS.
Related:
https://github.com/zowe/zowe-install-packaging/pull/1291

Add SSO variables to convert-env.sh

---

CHANGELOG.md
bin/zssServer.sh
defaults/serverConfig/server.json

Changes script to allow ZSS to be a separate component

---

package.json

Resolves https://github.com/zowe/zlux/issues/406
Thanks to @mkoipish

Add missing referenced library

---

CHANGELOG.md
bin/convert-env.sh
defaults/serverConfig/server.json
lib/initInstance.js
lib/initUtils.js
lib/upgradeInstance.js
lib/zluxArgs.js

Uses feature in https://github.com/zowe/zlux-server-framework/pull/212 to do a one-time upgrade for pre-existing bundled plugin references.

Upgrade process for making bundled plugins use ROOT_DIR

---

bin/convert-env.sh

Should resolve https://github.com/zowe/zlux/issues/483

Set a false on APIML if we know it is not in our environment

---

doc/swagger/fileapi.yaml

Signed-off-by: Akayeshmantha <akayeshmantha@apache.org>

Swagger doc for file change-mod endpoint.

---

bin/convert-env.sh

Fix as suggested by Vit

---

lib/initInstance.js

Component.json was only being created during upgrade opposed to initial installation

Create a component.json from a new instance

---

README.md
bin/convert-env.sh

Updating to restore CA code put into RC but not staging

---

bin/convert-env.sh

This pull request implements the following feature:
- Add ZOWE_LOOPBACK_ADDRESS and ZOWE_IP_ADDRESS to app server ip address array
Do not merge without: https://github.com/zowe/zlux-server-framework/pull/269
Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

Add ZOWE_LOOPBACK_ADDRESS and ZOWE_IP_ADDRESS to app server ip address array

---

bin/validate.sh

Simple fix for exit 0 prematurely killing program

---

bin/convert-env.sh
defaults/serverConfig/server.json
lib/zluxArgs.js

This PR sets up some default behavior as well as fixes bugs seen when working with staging and is needed to work with PR https://github.com/zowe/zlux-server-framework/pull/275

Set some defaults for use with zss through apiml

---

bin/convert-env.sh

Quick fix for dev environment missing vars

---

bin/convert-env.sh

Prerequisite for https://github.com/zowe/zlux-server-framework/pull/263

APIML Storage: Check if Caching Service enabled

---

bin/convert-env.sh
lib/upgradeInstance.js

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]
This PR depends upon the following PRs:
I will be testing this through zowe-install-packaging output.
The problem I am fixing is that when zss is available through apiml, app-server will ignore that on a full install for two reasons:
1) our decision making in the env files ignores content in server.json, so apiml mode is just disabled because the zss server name is not seen.
2) the zss server name should be in server.json but is not during an upgrade, because no upgrade action is performed to put it into that file.

Bugfix for not using zss through apiml when it is available

---

bin/convert-env.sh

This pr is https://github.com/zowe/zlux-app-server/pull/162  but for staging branch

Small workaround for zss-thru-apiml docker

---

bin/internal-install.sh
manifest.yaml

Move zlux unpackaging script from zowe install packaging to here

---

defaults/plugins/org.zowe.zlux.agent.json
defaults/plugins/org.zowe.zlux.json
lib/initInstance.js

- Add default plugin for swagger
- This PR addresses Issue: 
```
2021-05-13 22:34:37.016  ZWED0301I - Found recognizers in config for 'org.zowe.explorer-jes'
2021-05-13 22:34:37.018  ZWED0177W - Unable to load recognizers for 'org.zowe.explorer-jes' into config
2021-05-13 22:34:37.024  ZWED0301I - Found actions in config for 'org.zowe.explorer-jes'
2021-05-13 22:34:37.024  ZWED0177W - Unable to load actions for 'org.zowe.explorer-jes' into config
```
This PR depends upon the following PRs:
- [X ] Bug fix (non-breaking change which fixes an issue)

new swagger default plugin, plugin storage - app2app action/recognizers registeration

---

defaults/plugins/org.zowe.zlux.agent.json
defaults/plugins/org.zowe.zlux.json

Alternative to https://github.com/zowe/zlux-app-server/pull/170, keep plugins here but handle relativeTo at config time as we do with others.

Use upgrade process to make relativeTo rather than keeping it in repo

---

lib/initInstance.js

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]
This PR depends upon the following PRs:
Upgrade an existing instance. You will see that without this change, org.zowe.zlux.json is missing from the plugins folder, as is org.zowe.zlux.agent.json
This is because nothing checks for a discrepancy between default plugins and currently installed plugins during an upgrade.
Some plugins are not needed, and could be removed, so trying to make the two lists match is not necessary.
However, need some way to ensure certain plugins are always there.
A more robust solution than this would have been to …

Add missing apps by checking for one

---

CHANGELOG.md
bin/convert-env.sh

In the case that external and internal hostnames are not the same, app-server connects to the right discovery server but lists itself as coming from the wrong/misleading host.
Jack is testing this, so I will let him judge if this works.

switch external host to internal

---

bin/app-install-container.sh
bin/configure-container.sh
bin/install-container.sh
bin/internal-install.sh
bin/start-container.sh

Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>
This PR modifies script `internal-install.sh` to process tar packages in `files/zlux/*.tar`, script helps in processing `Dockerfile.zlux` to install tar packages.
And added new scripts for container
```
install-container.sh
configure-container.sh
start-container.sh
```
These scripts do what zowe-install-packaging do for native version
Added new for loop to untar packages from `files/zlux/*.tar` and copy them to `${ZOWE_ROOT_DIR}/components/app-server/share`
This PR addresses Issue: 
https://github.com/zowe/zlux-build/pull/63
This PR depends upon the following PRs:
- Code can be tested by testing new `Dockerfile.zlux` files in zlux-build
- …

add container scripts

---

bin/convert-env.sh

This sets a var which controls some optimizations in the app-server.

Set mode when applicable

---

CHANGELOG.md
bin/convert-env.sh

Sync cert verification flag

---

CHANGELOG.md
bin/convert-env.sh
bin/zss.apiml_static_reg_yaml_template.rs28.yml
zss.apiml_static_reg.yaml.template

This PR creates APIML static definition for zss when running in docker.

Create APIML static def for zss when running in docker

---

CHANGELOG.md
lib/initInstance.js
lib/initUtils.js
lib/upgradeInstance.js

Resolves https://github.com/zowe/zlux/issues/681 by adding a function to make it easy to add new plugins in future upgrades.
This also does some reorganization of the upgrade code to keep it clean.
I have not tested this yet but this should be tested by seeing if it resolves this previous problem: 
1) install zowe 1.22
2) upgrade to zowe 1.23
3) notice that IP explorer is missing
4) upgrade to this
5) notice IP explorer is now there.
Note: This is not testable in a dev environment, its a production thing.

Fix missing IP explorer

---

CHANGELOG.md
bin/app-install-container.sh
bin/app-server.sh
bin/configure-container.sh
bin/configure.sh
bin/convert-env.sh
bin/install-app.sh
bin/install-container.sh
bin/internal-install.sh
bin/start-container.sh
bin/start.sh
bin/zssServer.sh
lib/upgradeInstance.js

This is a build for @struga0258 to use to confirm if this new way of locating app-server directories will work properly under both the new container structure and the existing z/os structure. Most likely it will also work with server-bundle docker.

Enhance location logic for container use

---

bin/uninstall-app.sh

This is the reverse of install-app.sh. Greatly simplified in that it does not need nodejs to function, this only looks for the place in which to remove the .json file of an app if it exists.

Uninstall app script

---

lib/zluxArgs.js

We don't really need to print the list of environment variables we have in 2 different ways. Our startup scripts already print the env vars, and then our server attempts to print the same list soon after.
Soon after, the server also prints the config it is about to use, but does it per-worker so this just gets printed multiple times for no good reason. 
This PR attempts to reduce duplicate logging in those ways.

Reduce duplicate logging at startup

---

zss.apiml_static_reg.yaml.template

Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
Updated apiInfo.apiId to make zss static definition compatible with V2

[v2]updated apiInfo apiId

---

bin/convert-env.sh

This PR removes all PKCS#11 mentions(https://github.com/zowe/zss/issues/365)

Remove all PKCS#11 mentions

---

bin/convert-env.sh

This PR removes all PKCS#11 mentions(https://github.com/zowe/zss/issues/365)

[V2] Remove all PKCS#11 mentions

---

CHANGELOG.md
bin/convert-env.sh

Fix for https://github.com/zowe/community/issues/1391

Use log env var to know where to log to
