- bin/nodeCluster.sh
- bin/nodeServer.sh
- bin/zssServer.sh
Typo fix, plus making nodeCluster script behave as nodeServer script does, and fixing zssServer.sh such that the file env var utilizes the location of the script for relative path, to align to node script path behavior
> Script env var behavior alignment

- bin/nodeCluster.bat
- bin/nodeCluster.sh
- bin/nodeServer.bat
- bin/nodeServer.sh
- bin/zlux-install-script.sh
- js/zluxArgs.js
- js/zluxCluster.js
- js/zluxServer.js
- plugins/org.zowe.configjs.json
- plugins/org.zowe.terminal.proxy.json
- plugins/org.zowe.zlux.auth.trivial.json
zlux-proxy-server was renamed to zlux-server-framework, and zlux-example-server was renamed to zlux-app-server. There was some hardcoding so this should remedy it.
> Updating old proxy and example paths to app server and framework

- plugins/org.zowe.zossystem.subsystems.json
Removing zos subsystems app. It's not mature enough for default inclusion in 1.0.0, but hope to see it go back in for a future release
> Remove zos-subsystem app from 1.0.0

- README.md
Update README to reflect changes that add zowe-common-c to zss repo as a submodule
https://github.com/zowe/zss/pull/16
Signed-off-by: Dmitry Nikolaev <dnikolaev@rocketsoftware.com>
> Reflect in README ZSS having zowe-common-c as submodule

- config/tomcat.xml
- config/zluxserver.json
To utilize https://github.com/zowe/zlux-server-framework/pull/92 configuration changes are needed. This provides a tomcat xml configuration file which has substitutions for values that need to be determined dynamically, such as which port to listen on, depending on the quantity of servers needed.
This also specifies a new body in zluxserver.json which is needed to alert zlux to a configuration that can find & manage java & tomcat.
> Default configuration for tomcat usage

- bin/nodeCluster.sh
- bin/nodeServer.sh
'which' doesnt exist unless you have bash (most likely), so type is a safer command.
#! may or may not be read, but having no space is safer.
Signed-off-by: Sean Grady <sgrady@rocketsoftware.com>
> Small script fix for shebang, which to type

- bin/zssServer.sh
The z/OS UNIX `BPX1TLS` callable service can fail when attempting to create a surrogate thread using the identity of the client when the `_BPX_SHAREAS=YES` environment variable is set. 
If ZSS impersonation is enabled in a plugin when `BPX_SHAREAS=YES`  is set an "impersonation error" is returned and the log shows the following error. 
````
BPXTLS failed: rc=-1, return code=139, reason code=0x0be802af                                                 
Error: service has no impersonation; make sure process user has sufficient authority:                         
z/OS: program control flag must be set, UPDATE access to BPX.SERVER and BPX.DAEMON SAF resources is required
Other platforms: impersonation is not supported                                                             
```` …
> Fix impersonation error when _BPX_SHAREAS is set for local spawn

- lib/zluxArgs.js
- lib/zluxCluster.js
- lib/zluxServer.js
This pull request adds support for remapping server configuration.  The configLocation is exported from zluxArgs and consumed by the zluxCluster.js and zluxServer.js.  zluxArgs will no longer use CLI args if the config is rewritten (and the server reloaded).
Related:
https://github.com/zowe/zlux-server-framework/pull/137
> Rewrite config

- bin/nodeServer.bat
This pull request fixes the following bug:
Log location does not appear when executing ndoeServer.bat
Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>
> Bug fix: log location does not display with nodeServer.bat

- bin/install-app.bat
- bin/nodeCluster.bat
- bin/nodeCluster.sh
- bin/nodeServer.bat
- bin/nodeServer.sh
- bin/zssServer.sh
- config/zluxserver.json
- lib/zluxArgs.js
Change to enable D args, more options available from JSON, and some cleanup
> Configuration improvements part 1

- lib/zluxArgs.js
Utilizing the new functionality in https://github.com/zowe/zlux-server-framework/pull/156 to have env vars starting with ZWED_ or zwed_ to override what is in the JSON config file. CLI flags in turn override the env vars. However, env vars should not be read when doing a server dynamic reload, which only utilizes the content in the JSON.
> Merge env var object into config

- bin/configure.sh
- bin/convert-env.sh
Add more control over what the server should do when seeing apiml env vars. Enable/disable apiml-auth and discovery depending on env vars seen.
> More APIML configuration vars

- bin/install-app.sh
- lib/initInstance.js
InitInstance fix for copying default settings, plus install-app fix for not needing server to run before use, and using instance_dir bugfix
> install-app fix and initinstance removal of ncp

- README.md
Solves- https://github.com/zowe/zlux/issues/363
Currently, the documentation provided in the staging branch is less confusing to new users and developers.
But we get `file not found error` when following the steps 
This can be solved by checking out the `staging` branch rather than the `master` branch in the GitHub wiki 
Other solutions are also present
> Patching README in staging branch from master to staging - (Solves - #363) 

- lib/zluxArgs.js
CA is not required in the case of self-signing, and therefore does not need to be there for the defaults which use self-signing. Having the defaults put into lib/zluxArgs.js means that it is difficult to not have any CA, so this removes that restriction.
> Remove use of ca by default to allow using no ca

- lib/initInstance.js
Ignore umask if possible in order to avoid behavior that is out of the control of the code.
> Use 770 for instance file creation

- defaults/serverConfig/server.json
Use of https://github.com/zowe/zlux-server-framework/pull/180 to make it so that by default no plugins can be put into an iframe that is on a site outside the domain.
This needs testing: if this setting is wrong, content will not load properly in the browser.
> Add default for x-frame

- bin/convert-env.sh
- lib/zluxArgs.js
**Release note: Bugfix: app-server agent info was not available to plugins if it was specified via command line arguments**
Depends upon https://github.com/zowe/zlux-server-framework/pull/196
removed need to manage apiml inclusion or not, since it is redundant and that plugin will be replaced with sso auth. Added putting agent into configjson if specified over cli args
> Apiml handling cleanup

- lib/zluxArgs.js
Don't print at startup environment variables that contain PASSWORD or SECRET.
> Don't print PASSWORD and SECRET environment variables at startup

- bin/convert-env.sh
Release note: The app-server will favor and use a SAF keyring if defined for use in Zowe, rather than a unix file for keys, certificates, and certificate authorities.
Depends on https://github.com/zowe/zlux-server-framework/pull/206 for the app-server logic and https://github.com/zowe/zowe-install-packaging/pull/1177 for the keyring content and environment variables.
> Use saf keyrings if they are available

- bin/configure.sh
- defaults/ZLUX/pluginStorage/org.zowe.zlux.bootstrap/plugins/allowedPlugins.json
- defaults/serverConfig/server.json
- lib/upgradeInstance.js
Related to https://github.com/zowe/zowe-install-packaging/pull/1293
safsso plugin makes apiml-auth redundant, so it will be removed as a default to clean up the list.
> Update allowsPlugins list, remove apiml-auth default

- bin/convert-env.sh
Makes use of https://github.com/zowe/zowe-install-packaging/pull/1413 to enable the app server to use more than one CA.
> Use external root ca, if it exists

- CHANGELOG.md
- bin/convert-env.sh
InstanceID parameter within the server predates the environment variable, but is used by few. Primarily, it was used for RBAC resource naming. Therefore, to not disturb pre-existing ones, the server should only use the environment variable if it is non-default, since the env default is "1" while the app server's default was "0".
> Align instance ID when it is non-default

- bin/install-app.sh
Add option to write the json file without using nodejs.
This shouldn't be needed for most, but we've seen in one case a seemingly nodejs-releated issue with running the app install, yet the same nodejs did not have an issue running zowe itself.
While that sounds strange, this did allow us to successfully install apps, so this is a backup option hidden with an environment variable.
This actually is useful in the case you want to install a zss plugin without having nodejs.
Testing:
```
> ./install-app.sh ~/zlux-editor
Testing if node exists
node is /usr/local/bin/node
Running app-server plugin installer. Log=/dev/null
utils_path=~/zlux-server-framework/utils
app_path=~/zlux-editor
json_path=/home/sgrady/.zowe/workspace/app-server/serverConfig/server.json
2020-09-08 22:28:50.987 <ZWED:1660> …
```
> Write install json without nodejs

- CHANGELOG.md
- lib/initInstance.js
- lib/initUtils.js
Allow more env vars to configure terminals in more ways, and also post-install
The following new env vars would be supported in instance.env:
ZOWE_ZLUX_TELNET_HOST = string
ZOWE_ZLUX_SSH_HOST = string
ZOWE_ZLUX_TN3270_ROW = number
ZOWE_ZLUX_TN3270_COL = number
ZOWE_ZLUX_TN3270_MOD = numbers 2-5 as well as "dynamic" or other variations of the word
ZOWE_ZLUX_TN3270_CODEPAGE = ccsid number or string as seen in the ui
Resolves https://github.com/zowe/zowe-install-packaging/issues/1176
Resolves https://github.com/zowe/zowe-install-packaging/issues/1125
> Advanced terminal config via env var

- lib/initInstance.js
New code to handle terminal settings was given a list of plugins that was based on the initial state of when configuration was run.
If the list is empty, default plugins get registered which should result in the list containing those plugins, but this list did not get updated, so there was a state for configuration in which terminal settings were not set as a result.
> Fix case where server would end up with no plugins

- CHANGELOG.md
- bin/convert-env.sh
DO NOT MERGE WITHOUT:
https://github.com/zowe/zowe-install-packaging/pull/1742
Related:
https://github.com/zowe/zlux-server-framework/pull/254
This pull request fixes the following bug:
- External certificate authorities are not registered with the app server properly and may contribute to a SELF_SIGNED_CERT_IN_CHAIN error when using the mediation layer.
Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>
> Add external CA certs to app-server CA array

- bin/configure.sh
From https://github.com/zowe/zlux-app-server/pull/144 there was one reference to set-node that was not updated, causing failure.
> Fix missing file that was renamed

- bin/install-app.sh
In the case that install-app.sh is not within the bin folder of zlux-app-server, need to use variables to figure out where to find the internal-node-init.sh script.
> Call internal-node-init.sh from variable path

- bin/app-server.bat
- bin/app-server.sh
This pull request implements the following feature:
- Allow the app-server working directory to be configured via environment variable. By default, the current working directory is ${zlux-app-server component dir}/lib which may be read only in some cases.
Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>
> Enable app-server working directory to be configurable

- CHANGELOG.md
- bin/convert-env.sh
Certain parts of our server get the hostname by querying the system in a way that may result in an incorrect or short hostname, rather than a correct and fully qualified one.
But, the correct value is already recorded in the zowe environment, so we should use it when possible.
Resolves https://github.com/zowe/zlux/issues/566
> Set hostname based on zowe environment

- bin/convert-env.sh
- lib/zluxArgs.js
Related PRs:
- TLS Support zowe/zss#226
- Cipher suite definitions zowe/zowe-common-c#199
- TLS support for ZSS agent zowe/zlux-server-framework#271
Linked issue: zowe/zlux#632
> Automate TLS setup for zss

- bin/convert-env.sh
workaround for docker trying to connect to zss thru apiml when its not found there
In our codebase, we assume zss can be found on the apiml if we can construct a url to it and find the apiml to be running.
However, zss is only available there when a static def file is set up, which only happens when zss and apiml are in the same place. In docker, that's not true and therefore we can't connect to zss in this way. For now, this is a temporarily workaround to disable this feature for docker.
Run the latest docker image. You'll see the error
`ZWED0151W - unhandledRejection Error: Call timeout when fetching agent status from APIML`
With this PR, …
> Docker zss-thru-apiml workaround

- bin/convert-env.sh
The OSNAME used in PR #162 did not have an initial value, so the check would have been false in all cases, leading to what we wanted on docker but not on z/os.
> Add missing env var init

- README.md
This is a small README change to make note of sample app dependencies that people often get confused about, as well as to update the ZSS config section to note the simple install of sso-auth and that ZSS has another way to do HTTPS these days.
> Update README to be consistent with modern settings and facts

- lib/zluxArgs.js
This PR add `/user-info` endpoint to the list of proxied agent services.
This PR depends upon the following PRs: https://github.com/zowe/zss/pull/336
> Add user-info to the list of agent services

- bin/install-app.sh
This is meant to allow install-app to work in the containers other than the app-server's own container.
In this mode, install-app.sh will live in the instance, but zlux-core will not be there.
So, we activate "nojs" mode, which does not need zlux-core. The install skips validation but does write the install file.
Do existing regression tests about
- Can I install an app in a dev env
- Can I install an app on z/os (before&after initial run)
Now test new case:
Before PR: explorers dont show up in container desktop
After PR: explorers do show up.
> Update install-app to work better in container

- lib/zluxArgs.js
This PR merges the config from `zowe.yaml` into the final app-server config.
This PR depends upon the following PRs: 
* https://github.com/zowe/zlux-server-framework/pull/333
```yaml
app-server:
enabled: true
port: "59344"
certificate:
keystore:
alias: app-server
pem:
key: /u/ts3105/keystore-ha/localhost/localhost.keystore.app-server.key
certificate: /u/ts3105/keystore-ha/localhost/localhost.keystore.app-server.cer-ebcdic
logLevels:
"_zsf.utils": 4
node:
https: 
enableTrace: true
zss:
enabled: true
port: "59342"
crossMemoryServerName: ZWESIS_STD
tls: true
certificate:
keystore:
alias: zss
agent:
mediationLayer:
enabled: false
```
> Load zowe.yaml
